// Next's own types (node_modules/next/types/global.d.ts) declare '*.module.css'
// and '*.module.scss' but not plain '*.css', so a side-effect import such as
// `import './capability.css'` resolves to nothing and TS reports 2882 under
// moduleResolution: bundler.
//
// This lives in the repo rather than next-env.d.ts because that file is
// gitignored and only regenerated by `next dev`/`next build` — a fresh clone
// would show the error again before the first build.
declare module '*.css';
